<?php
ob_start();
?>

<div class="max-w-2xl mx-auto py-12">
    <div class="flex items-center justify-between mb-8">
        <h1 class="text-2xl font-bold">My Profile</h1>
        <a href="<?php echo $base; ?>/user/pastes" class="border border-zinc-700 hover:bg-zinc-800 px-4 py-2 rounded-lg text-sm transition-colors">My Pastes</a>
    </div>
    <div class="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-8 rounded-3xl shadow-2xl">

        <form action="<?php echo $base; ?>/profile/edit" method="POST" class="space-y-6">
            <input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>">

            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">Username</label>
                <div class="relative">
                    <i data-lucide="user" class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"></i>
                    <input type="text" disabled value="<?php echo \App\Helpers\View::e($user['username']); ?>" class="w-full bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-200 dark:border-zinc-800 rounded-xl pl-12 pr-4 py-3 text-zinc-500 cursor-not-allowed">
                </div>
                <p class="text-[10px] text-zinc-600 mt-1">Keep autogenerated name? You can change it once.</p>
            </div>

            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">Full name</label>
                <div class="relative">
                    <i data-lucide="contact" class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"></i>
                    <input type="text" name="full_name" value="<?php echo \App\Helpers\View::e($user['full_name']); ?>" class="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white rounded-xl pl-12 pr-4 py-3 focus:outline-none focus:border-indigo-500 transition-all">
                </div>
            </div>

            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">Email</label>
                <div class="relative">
                    <i data-lucide="mail" class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"></i>
                    <input type="email" disabled value="<?php echo \App\Helpers\View::e($user['email']); ?>" class="w-full bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-200 dark:border-zinc-800 rounded-xl pl-12 pr-4 py-3 text-zinc-500 cursor-not-allowed">
                </div>
            </div>


            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">Bio / About Me</label>
                <textarea name="bio" rows="4" class="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white rounded-xl px-4 py-3 focus:outline-none focus:border-indigo-500 transition-all" placeholder="Tell us about yourself..."><?php echo \App\Helpers\View::e($user['bio']); ?></textarea>
            </div>

            <div class="pt-4 flex gap-4">
                <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-3 rounded-xl font-bold transition-all">
                    Save Changes
                </button>
                <a href="<?php echo $base; ?>/dashboard" class="bg-zinc-800 hover:bg-zinc-700 text-white px-8 py-3 rounded-xl font-bold transition-all">
                    Cancel
                </a>
            </div>
        </form>

        <div class="border-t border-zinc-800 my-10"></div>

        <h2 class="text-xl font-bold mb-6 text-center">Change Password</h2>
        <form action="<?php echo $base; ?>/profile/password" method="POST" class="space-y-6">
            <input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>">
            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">Current Password</label>
                <div class="relative">
                    <i data-lucide="key" class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"></i>
                    <input type="password" name="current_password" required placeholder="••••••••" class="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white rounded-xl pl-12 pr-4 py-3 focus:outline-none focus:border-indigo-500 transition-all">
                </div>
            </div>
            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">New Password</label>
                <div class="relative">
                    <i data-lucide="edit-3" class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"></i>
                    <input type="password" name="new_password" required placeholder="New Password" class="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white rounded-xl pl-12 pr-4 py-3 focus:outline-none focus:border-indigo-500 transition-all">
                </div>
            </div>
            <div>
                <label class="block text-sm font-medium text-zinc-500 mb-2">Confirm Password</label>
                <div class="relative">
                    <i data-lucide="check" class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"></i>
                    <input type="password" name="confirm_password" required placeholder="Confirm Password" class="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white rounded-xl pl-12 pr-4 py-3 focus:outline-none focus:border-indigo-500 transition-all">
                </div>
            </div>
            <button type="submit" class="w-full bg-zinc-900 border border-zinc-800 hover:bg-zinc-800 text-white px-8 py-3 rounded-xl font-bold transition-all shadow-lg">
                Submit
            </button>
        </form>

        <div class="border-t border-zinc-800 my-10"></div>

        <div class="bg-red-500/5 border border-red-500/20 p-6 rounded-2xl">
            <h3 class="text-red-500 font-bold mb-2">Danger Zone</h3>
            <p class="text-zinc-500 text-sm mb-4">Once you delete your account, there is no going back. Please be certain.</p>
            <form action="<?php echo $base; ?>/profile/delete" method="POST" onsubmit="return confirm('Are you absolutely sure you want to delete your account? All your pastes will be permanently deleted.');">
                <input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>">
                <button type="submit" class="bg-red-600 hover:bg-red-700 text-white px-6 py-2 rounded-lg text-sm font-bold transition-all flex items-center gap-2">
                    <i data-lucide="trash-2" class="w-4 h-4"></i> Delete My Account
                </button>
            </form>
        </div>
    </div>
</div>

<?php
$content = ob_get_clean();
include __DIR__ . '/../layouts/main.php';
?>
